# Generated by Django 4.2.11 on 2024-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cimage',
            field=models.ImageField(blank=True, upload_to='categoryimages'),
        ),
    ]
